config/routes.rb
Rails.application.routes.draw do
  root 'sentiment#index'

  post 'analyze', to: 'sentiment#analyze'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sentiment_controller.rb
class SentimentController < ApplicationController
  def index
  end

  def analyze
    keywords = params[:keywords].split(/\r\n/)
    feeds = params[:feeds].split(/\r\n/)

    sentiment = BitcoinSentiment.build(keywords: keywords, feeds: feeds, api_key: params[:api_key])
    @results = sentiment.fetch
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def class_for_sentiment(value)
    if value > 0
      'success'
    elsif value < 0
      'danger'
    else
      'active'
    end
  end

  def text_for_sentiment(value)
    if value > 0
      'Positive'
    elsif value < 0
      'Negative'
    else
      'Neutral'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bitcoin Sentiment" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bitcoin Sentiment</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!-- <li><%= link_to "Link", "/path1"  %></li> -->
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="well sidebar-nav">
            <h3>Analyze</h3>

            <%= form_tag analyze_path, method: :post do %>
              <div class="form-group">
                <label for="api_key">Alchemy API Key</label>
                <input type="text" class="form-control" id="api_key" placeholder="Enter your Alchemy API Key" name="api_key" value="<%= params[:api_key] %>">
              </div>
              <div class="form-group">
                <label for="feeds">Feeds</label>
                <textarea class="form-control" rows="5" id="feeds" name="feeds"><%= params[:feeds] %></textarea>
              </div>
              <div class="form-group">
                <label for="keywords">Keywords</label>
                <textarea class="form-control" rows="5" id="keywords" name="keywords"><%= params[:keywords] %></textarea>
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            <% end %>


          </div><!--/.well -->
        </div><!--/span-->

        <div class="col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Gennovacap <%= Time.zone.now.year %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/sentiment/analyze.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Sentiment</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |keyword, values| %>
      <% values.each do |value| %>
        <tr class="<%= class_for_sentiment(value) %>">
          <td><%= keyword %></td>
          <td><%= text_for_sentiment(value) %> (<%= value %>)</td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<pre>
  <%= @results.to_json %>
</pre>

app/views/sentiment/index.html.erb
<div class="well">
  Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Aenean lacinia bibendum nulla sed consectetur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
</div>